language: elixir
elixir:
  - 1.7.3
  - 1.8
  - 1.9
otp_release:
  - 21.0
  - 22.0

env:
 global:
   - MIX_ENV=test
   - PRONTO_PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST

before_script:
  - rvm install ruby-2.3.1
  - gem install pronto-credo

script:
  - if [ $PULL_REQUEST_ID != false ]; then pronto run -f github_pr; fi
  - mix test
  - mix coveralls.json
  - bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"
  - cd sample_application
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

cache:
 directories:
   - /home/travis/.rvm/
   - /home/travis/otp/
   - /home/travis/.kiex/
