language: elixir
elixir:
  - 1.8
  - 1.9
otp_release:
  - 22.0

env:
 global:
   - MIX_ENV=test
before_script:
  - mix deps.compile
  
script:
  - mix coveralls.json
  - bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"
  - cd sample_application
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

cache:
 directories:
   - /home/travis/otp/
   - /home/travis/.kiex/
   - /home/travis/deps/
   - /home/travis/_build/
